"use client";
import {FormEvent,useEffect,useState} from "react";
import type {Session} from "@supabase/supabase-js";
import {supabase} from "../lib/supabase";
import {GAMES} from "../lib/games";
type Profile={id:string;display_name:string;avatar_color:string}; type Couple={id:string;member_one:string;member_two:string|null;invite_code:string}; type Night={id:string;couple_id:string;room_code:string;status:string;current_game_index:number;current_round:number;created_by:string}; type View="home"|"setup"|"lobby"|"play"|"results"|"history"|"leaderboard"|"profile";
const init=(s?:string)=>s?.trim().slice(0,1).toUpperCase()||"?";
export default function Home(){
 const[session,setSession]=useState<Session|null>(null),[loading,setLoading]=useState(true),[profile,setProfile]=useState<Profile|null>(null),[partner,setPartner]=useState<Profile|null>(null),[couple,setCouple]=useState<Couple|null>(null),[view,setView]=useState<View>("home"),[selected,setSelected]=useState(["knows","trivia","five"]),[night,setNight]=useState<Night|null>(null),[players,setPlayers]=useState<any[]>([]),[gi,setGi]=useState(0),[round,setRound]=useState(0),[answer,setAnswer]=useState(""),[answers,setAnswers]=useState<any[]>([]),[score,setScore]=useState(0),[history,setHistory]=useState<any[]>([]),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{supabase.auth.getSession().then(x=>{setSession(x.data.session);setLoading(false)});const{data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(session?.user)loadAccount(session.user.id)},[session?.user?.id]);
 useEffect(()=>{if(!night)return;const ch=supabase.channel("twofold-night-"+night.id).on("postgres_changes",{event:"*",schema:"public",table:"twf_game_nights",filter:"id=eq."+night.id},p=>{const n=p.new as Night;setNight(n);setGi(n.current_game_index);setRound(n.current_round);if(n.status==="playing")setView("play");if(n.status==="completed")setView("results")}).on("postgres_changes",{event:"*",schema:"public",table:"twf_game_night_players",filter:"game_night_id=eq."+night.id},()=>loadPlayers(night.id)).on("postgres_changes",{event:"INSERT",schema:"public",table:"twf_answers"},p=>setAnswers(a=>[...a.filter(x=>x.id!==(p.new as any).id),p.new])).subscribe();return()=>{supabase.removeChannel(ch)}},[night?.id]);
 async function loadAccount(uid:string){setLoading(true);const{data:p}=await supabase.from("twf_profiles").select("*").eq("id",uid).maybeSingle();setProfile(p);if(p){const{data:c}=await supabase.from("twf_couples").select("*").or("member_one.eq."+uid+",member_two.eq."+uid).neq("status","ended").maybeSingle();setCouple(c);if(c){const pid=c.member_one===uid?c.member_two:c.member_one;if(pid){const{data:pp}=await supabase.from("twf_profiles").select("*").eq("id",pid).single();setPartner(pp)}const{data:h}=await supabase.from("twf_game_nights").select("*").eq("couple_id",c.id).eq("status","completed").order("completed_at",{ascending:false});setHistory(h||[])}}setLoading(false)}
 async function makeProfile(name:string){setBusy(true);const{error}=await supabase.from("twf_profiles").insert({id:session!.user.id,display_name:name});if(error)setMsg(error.message);else await loadAccount(session!.user.id);setBusy(false)}
 async function makeCouple(){setBusy(true);const{data,error}=await supabase.from("twf_couples").insert({member_one:profile!.id,name:profile!.display_name+" couple"}).select().single();if(error)setMsg(error.message);else setCouple(data);setBusy(false)}
 async function joinCouple(code:string){setBusy(true);const{error}=await supabase.rpc("twf_join_couple",{code});if(error)setMsg(error.message);else await loadAccount(profile!.id);setBusy(false)}
 async function makeNight(){if(!couple)return;setBusy(true);const{data:n,error}=await supabase.from("twf_game_nights").insert({couple_id:couple.id,created_by:profile!.id}).select().single();if(error){setMsg(error.message);setBusy(false);return}await supabase.from("twf_game_night_players").insert([{game_night_id:n.id,user_id:profile!.id,ready:true},...(partner?[{game_night_id:n.id,user_id:partner.id,ready:false}]:[])]);await supabase.from("twf_selected_games").insert(selected.map((game_key,position)=>({game_night_id:n.id,game_key,position})));setNight(n);await loadPlayers(n.id);setView("lobby");setBusy(false)}
 async function joinRoom(code:string){const{data:n,error}=await supabase.from("twf_game_nights").select("*").eq("room_code",code.toUpperCase()).single();if(error){setMsg("Room not found.");return}await supabase.from("twf_game_night_players").upsert({game_night_id:n.id,user_id:profile!.id,ready:true});setNight(n);await loadPlayers(n.id);setView("lobby")}
 async function loadPlayers(id:string){const{data}=await supabase.from("twf_game_night_players").select("*").eq("game_night_id",id);setPlayers(data||[])}
 async function start(){await supabase.from("twf_game_nights").update({status:"playing",started_at:new Date().toISOString()}).eq("id",night!.id);setView("play")}
 async function submit(){if(!answer.trim())return;const{data:sg}=await supabase.from("twf_selected_games").select("*").eq("game_night_id",night!.id).eq("position",gi).single();let{data:r}=await supabase.from("twf_rounds").select("*").eq("selected_game_id",sg.id).eq("round_number",round).maybeSingle();if(!r){const made=await supabase.from("twf_rounds").insert({selected_game_id:sg.id,round_number:round,prompt:{text:game.prompts[round%3]}}).select().single();r=made.data}const points=game.mode==="speed"?100:75;const out=await supabase.from("twf_answers").upsert({round_id:r.id,user_id:profile!.id,answer:{value:answer},points},{onConflict:"round_id,user_id"}).select().single();if(!out.error){setAnswers(x=>[...x.filter(v=>v.user_id!==profile!.id),out.data]);setScore(s=>s+points);setAnswer("")}}
 async function advance(){if(round<2){setRound(round+1);setAnswers([]);await supabase.from("twf_game_nights").update({current_round:round+1}).eq("id",night!.id)}else if(gi<selected.length-1){setGi(gi+1);setRound(0);setAnswers([]);await supabase.from("twf_game_nights").update({current_game_index:gi+1,current_round:0}).eq("id",night!.id)}else{await supabase.from("twf_game_night_players").update({total_score:score}).eq("game_night_id",night!.id).eq("user_id",profile!.id);await supabase.from("twf_game_nights").update({status:"completed",winner_id:profile!.id,completed_at:new Date().toISOString()}).eq("id",night!.id);setView("results");await loadAccount(profile!.id)}}
 if(loading)return <div className="splash"><div className="logoMark">T</div><p>Preparing Twofold…</p></div>; if(!session)return <Auth/>; if(!profile)return <Onboard action={makeProfile} busy={busy} msg={msg}/>; if(!couple)return <Pair profile={profile} create={makeCouple} join={joinCouple} busy={busy} msg={msg}/>;
 const game=GAMES.find(g=>g.key===selected[gi])||GAMES[0],prompt=game.prompts[round%3];
 return <div className="shell"><aside><button className="brand" onClick={()=>setView("home")}><i>T</i>Twofold</button><nav>{[["⌂","Home","home"],["♕","Leaderboard","leaderboard"],["◷","Game history","history"],["♙","Couple profile","profile"]].map(x=><button key={x[1]} className={view===x[2]?"active":""} onClick={()=>setView(x[2] as View)}><b>{x[0]}</b>{x[1]}</button>)}</nav><div className="online">● &nbsp; {partner?partner.display_name+" linked":"Invite pending"}<small>{partner?"Private couple space":"Code: "+couple.invite_code}</small></div><button className="profile"><span>{init(profile.display_name)}</span><div><b>{profile.display_name}</b><small>{partner?"Playing with "+partner.display_name:"Waiting for partner"}</small></div></button></aside><main><header><strong>Twofold</strong><button className="signout" onClick={()=>supabase.auth.signOut()}>Sign out</button></header>{msg&&<div className="toast" onClick={()=>setMsg("")}>{msg} ×</div>}
 {view==="home"&&<div className="page"><section className="hero"><div><small>— YOUR PRIVATE GAME SPACE</small><h1>Play together.<br/><em>Remember everything.</em></h1><p>{partner?"You and "+partner.display_name+" are ready for another round.":"Share your couple code to connect."}</p><button className="primary" disabled={!partner} onClick={()=>setView("setup")}>＋ Create game night</button></div></section><div className="title"><div><small>YOUR SPACE</small><h2>Good evening, {profile.display_name}</h2></div></div><section className="stats"><article className="score"><small>GAME NIGHTS</small><h3>{history.length}</h3><p>Completed together</p></article><article><sup>♕</sup><small>GAMES AVAILABLE</small><h3>{GAMES.length}</h3><p>All playable</p></article><article><sup>↗</sup><small>COUPLE CODE</small><h3>{couple.invite_code}</h3><p>Private to both partners</p></article></section><section className="joinbox"><div><small>JOIN ACTIVE ROOM</small><h2>Have a room code?</h2></div><CodeForm label="Join room" action={joinRoom}/></section></div>}
 {view==="setup"&&<div className="page"><button className="back" onClick={()=>setView("home")}>← Back</button><div className="setupHead"><div><small>GAME NIGHT · STEP 1 OF 2</small><h1>Build tonight’s lineup</h1><p>Select exactly what you want to play.</p></div><div className="count"><b>{selected.length}</b> selected</div></div><div className="games">{GAMES.map(g=><button key={g.key} className={selected.includes(g.key)?"selected":""} onClick={()=>setSelected(s=>s.includes(g.key)?s.filter(x=>x!==g.key):[...s,g.key])}><i>{selected.includes(g.key)?"✓":"+"}</i><b className="gameIcon">{g.icon}</b><small>{g.category}</small><h3>{g.title}</h3><p>{g.instructions}</p></button>)}</div><footer><span>{selected.length} games · About {selected.length*4} min</span><button className="primary" disabled={selected.length<2||busy} onClick={makeNight}>Create room →</button></footer></div>}
 {view==="lobby"&&night&&<div className="center"><small>PRIVATE GAME NIGHT</small><h1>Your room is ready</h1><p>Both devices update automatically.</p><div className="code"><b>{night.room_code}</b><button onClick={()=>navigator.clipboard.writeText(night.room_code)}>▣ Copy</button></div><div className="players"><div><i>{init(profile.display_name)}</i><h3>{profile.display_name}</h3><small>Ready</small></div><b>·· VS ··</b><div><i className="rose">{init(partner?.display_name)}</i><h3>{partner?.display_name}</h3><small>{players.find(p=>p.user_id===partner?.id)?.ready?"Ready":"Joining…"}</small></div></div><button className="primary wide" onClick={start}>Start game night →</button></div>}
 {view==="play"&&<div className="play"><div className="playTop"><button onClick={()=>setView("home")}>×</button><div><small>GAME {gi+1} OF {selected.length}</small><b>{game.title}</b></div><span>Score <b>{score}</b></span></div><div className="progress"><i style={{width:(((gi*3+round+1)/(selected.length*3))*100)+"%"}}/></div><section className="question"><small>ROUND {round+1} · {game.category.toUpperCase()}</small><h1>{prompt}</h1><p>{game.instructions}</p>{game.mode==="choice"?<div>{[profile.display_name,partner?.display_name||"Partner"].map(x=><button key={x} className={answer===x?"chosen":""} onClick={()=>setAnswer(x)}>{x}</button>)}</div>:<textarea value={answer} onChange={e=>setAnswer(e.target.value)} placeholder={game.mode==="speed"?"Answer quickly…":"Type your answer…"} maxLength={500}/>}<button className="primary" disabled={!answer.trim()} onClick={submit}>Lock in answer</button><p className="answerStatus">{answers.some(a=>a.user_id===profile.id)?"✓ Your answer is locked":"Waiting for you"} · {answers.some(a=>a.user_id===partner?.id)?"Partner answered":"Partner is thinking…"}</p><button className="secondary nextRound" onClick={advance}>{round<2?"Next round":gi<selected.length-1?"Next game":"Finish"} →</button></section></div>}
 {view==="results"&&<div className="center results"><div className="cup">♕</div><small>GAME NIGHT COMPLETE</small><h1>Saved to your history!</h1><p>Your final score is {score} points.</p><button className="primary" onClick={()=>{setScore(0);setGi(0);setRound(0);setView("setup")}}>Play again</button></div>}
 {view==="history"&&<Simple title="Game-night history" intro="Every completed night is saved.">{history.length?history.map(h=><div className="historyRow" key={h.id}><span>♡</span><div><b>Room {h.room_code}</b><small>{new Date(h.completed_at).toLocaleDateString()}</small></div><strong>Completed</strong></div>):<p>No completed nights yet.</p>}</Simple>}
 {view==="leaderboard"&&<Simple title="The friendly rivalry" intro="All-time game-night wins."><div className="leaders"><div><i>{init(profile.display_name)}</i><h2>{profile.display_name}</h2><strong>{history.filter(h=>h.winner_id===profile.id).length}</strong><small>WINS</small></div><span>━━━━ ● ━━━━</span><div><i className="rose">{init(partner?.display_name)}</i><h2>{partner?.display_name}</h2><strong>{history.filter(h=>h.winner_id===partner?.id).length}</strong><small>WINS</small></div></div></Simple>}
 {view==="profile"&&<Simple title="Your couple space" intro="Only you and your linked partner can see this data."><div className="accountCard"><h3>{profile.display_name} & {partner?.display_name||"Partner"}</h3><p>Couple code: <b>{couple.invite_code}</b></p><p>{session.user.email}</p><button className="secondary" onClick={()=>supabase.auth.resetPasswordForEmail(session.user.email!,{redirectTo:location.origin})}>Send password-reset email</button></div></Simple>}</main></div>}
function Auth(){const[mode,setMode]=useState<"login"|"signup"|"forgot">("login"),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);async function go(e:FormEvent){e.preventDefault();setBusy(true);const r=mode==="signup"?await supabase.auth.signUp({email,password,options:{emailRedirectTo:location.origin}}):mode==="forgot"?await supabase.auth.resetPasswordForEmail(email,{redirectTo:location.origin}):await supabase.auth.signInWithPassword({email,password});setMsg(r.error?.message||(mode==="signup"?"Check your email to confirm your account.":mode==="forgot"?"Reset email sent.":""));setBusy(false)}return <div className="authPage"><section className="authBrand"><div className="logoMark">T</div><h1>Game night,<br/><em>just for two.</em></h1><p>Choose games, play live, and keep the rivalry going.</p></section><section className="authPanel"><div><small>WELCOME TO TWOFOLD</small><h2>{mode==="login"?"Sign in":mode==="signup"?"Create your account":"Reset password"}</h2><form onSubmit={go}><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label>{mode!=="forgot"&&<label>Password<input type="password" minLength={8} required value={password} onChange={e=>setPassword(e.target.value)}/></label>}<button className="primary" disabled={busy}>{busy?"Please wait…":mode==="login"?"Sign in":mode==="signup"?"Create account":"Send reset email"}</button></form><button className="google" onClick={()=>supabase.auth.signInWithOAuth({provider:"google",options:{redirectTo:location.origin}})}>G &nbsp; Continue with Google</button>{msg&&<p className="formMsg">{msg}</p>}<div className="authLinks"><button onClick={()=>setMode(mode==="signup"?"login":"signup")}>{mode==="signup"?"Sign in instead":"Create an account"}</button><button onClick={()=>setMode("forgot")}>Forgot password?</button></div></div></section></div>}
function Onboard({action,busy,msg}:{action:(n:string)=>void;busy:boolean;msg:string}){const[n,setN]=useState("");return <div className="soloCard"><div className="logoMark">T</div><small>ONE LAST STEP</small><h1>Create your profile</h1><p>Choose the name your partner will see.</p><input value={n} onChange={e=>setN(e.target.value)} maxLength={40} placeholder="Display name"/><button className="primary" disabled={!n.trim()||busy} onClick={()=>action(n.trim())}>Continue</button>{msg&&<p>{msg}</p>}</div>}
function Pair({profile,create,join,busy,msg}:{profile:Profile;create:()=>void;join:(x:string)=>void;busy:boolean;msg:string}){return <div className="soloCard"><div className="logoMark">T</div><small>WELCOME, {profile.display_name.toUpperCase()}</small><h1>Connect your couple</h1><p>One partner creates the space. The other joins with its private code.</p><button className="primary" disabled={busy} onClick={create}>Create couple space</button><span>or</span><CodeForm label="Join couple" action={join}/>{msg&&<p>{msg}</p>}</div>}
function CodeForm({label,action}:{label:string;action:(x:string)=>void}){const[c,setC]=useState("");return <form className="codeForm" onSubmit={e=>{e.preventDefault();if(c.trim())action(c)}}><input value={c} onChange={e=>setC(e.target.value.toUpperCase())} placeholder="Enter code"/><button>{label}</button></form>}
function Simple({title,intro,children}:{title:string;intro:string;children:React.ReactNode}){return <div className="page board"><small>TWOFOLD</small><h1>{title}</h1><p>{intro}</p>{children}</div>}
