export type GameMode="match"|"choice"|"text"|"speed"|"creative";
export type GameDef={key:string;title:string;icon:string;category:string;mode:GameMode;instructions:string;prompts:string[]};
export const GAMES:GameDef[]=[
{key:"knows",title:"Who Knows Me Better?",icon:"♡",category:"Couple",mode:"match",instructions:"Answer about yourself, then your partner predicts it.",prompts:["My perfect day includes…","My favourite way to relax is…","The snack I can never refuse is…"]},
{key:"guess",title:"Guess My Answer",icon:"✦",category:"Couple",mode:"match",instructions:"Write an answer and score when your answers match.",prompts:["Our funniest shared memory","A trip we should take","The song that reminds me of us"]},
{key:"likely",title:"Most Likely To",icon:"☻",category:"Couple",mode:"choice",instructions:"Choose which partner best fits the prompt.",prompts:["Who is most likely to plan a surprise?","Who takes longer to choose food?","Who would win a dance-off?"]},
{key:"would",title:"Would You Rather?",icon:"↔",category:"Couple",mode:"choice",instructions:"Choose privately, then reveal whether you agree.",prompts:["Beach sunrise or city night?","Plan every detail or be spontaneous?","Cook together or order your favourite meal?"]},
{key:"finish",title:"Finish My Sentence",icon:"…",category:"Couple",mode:"match",instructions:"Complete the sentence and predict your partner.",prompts:["I knew you understood me when…","We always laugh when…","Next year, I hope we…"]},
{key:"memory",title:"Memory Lane",icon:"⌁",category:"Couple",mode:"text",instructions:"Recall a shared moment; compare details together.",prompts:["Describe your first favourite memory together.","What small moment still makes you smile?","What was your best unexpected adventure?"]},
{key:"timeline",title:"Relationship Timeline",icon:"⌛",category:"Couple",mode:"text",instructions:"Place relationship moments in the correct order.",prompts:["List three important moments in order.","Which happened first: your first long call or first outing?","Name the month of a favourite milestone."]},
{key:"said",title:"Who Said It?",icon:"“",category:"Couple",mode:"choice",instructions:"Guess which partner said the quote.",prompts:["I could eat this every day.","Five more minutes, then I’m ready.","Let’s take one more picture."]},
{key:"trivia",title:"Trivia Battle",icon:"?",category:"Competitive",mode:"speed",instructions:"Answer correctly before your partner.",prompts:["What is the largest planet?","How many sides does a hexagon have?","What is the capital of Jamaica?"]},
{key:"riddle",title:"Riddle Battle",icon:"◈",category:"Competitive",mode:"speed",instructions:"Solve the riddle first.",prompts:["What has keys but opens no locks?","What gets wetter as it dries?","What has hands but cannot clap?"]},
{key:"math",title:"Math Battle",icon:"∑",category:"Competitive",mode:"speed",instructions:"Solve the equation before time expires.",prompts:["18 × 7","144 ÷ 12","35 + 48 − 19"]},
{key:"word",title:"Word Battle",icon:"Aa",category:"Competitive",mode:"speed",instructions:"Enter a valid word for the challenge.",prompts:["A 6-letter word starting with S","A word that rhymes with light","A fruit containing the letter A"]},
{key:"emoji",title:"Emoji Decoder",icon:"☺",category:"Competitive",mode:"speed",instructions:"Decode the emoji phrase.",prompts:["🌧️🐱🐶","⏰💰","📖🐛"]},
{key:"memoryChallenge",title:"Memory Challenge",icon:"▦",category:"Competitive",mode:"speed",instructions:"Study the sequence, then reproduce it.",prompts:["♡ ✦ ☻ ◈ ♕","7 2 9 4 1","Red · Blue · Gold · Green"]},
{key:"five",title:"5 Second Challenge",icon:"5",category:"Party",mode:"speed",instructions:"Name three things before time runs out.",prompts:["Name 3 date ideas","Name 3 things that are blue","Name 3 songs you both know"]},
{key:"charades",title:"Charades",icon:"♙",category:"Party",mode:"creative",instructions:"Act out the prompt without speaking.",prompts:["Taking a selfie","Missing the bus","Winning a race"]},
{key:"dontsay",title:"Don’t Say It",icon:"×",category:"Party",mode:"text",instructions:"Describe the word without using the forbidden clues.",prompts:["Beach — don’t say sand, sea, water","Birthday — don’t say cake, age, party","Phone — don’t say call, screen, text"]},
{key:"truth",title:"Two Truths & a Lie",icon:"≋",category:"Party",mode:"text",instructions:"Write three statements; your partner spots the lie.",prompts:["Write your two truths and one lie.","Use only childhood memories.","Use only food and travel facts."]},
{key:"describe",title:"Describe & Guess",icon:"◎",category:"Party",mode:"text",instructions:"Describe the secret prompt for your partner.",prompts:["Sunset","Roller coaster","Birthday cake"]},
{key:"draw",title:"Drawing Battle",icon:"✎",category:"Creative",mode:"creative",instructions:"Draw the prompt and let your partner guess.",prompts:["Dream house","A dancing cat","Your perfect weekend"]},
{key:"caption",title:"Caption This",icon:"“ ”",category:"Creative",mode:"creative",instructions:"Write the funniest caption; vote on the winner.",prompts:["When the food finally arrives…","That look when you both forgot…","Our next adventure starts like this…"]},
{key:"story",title:"Finish the Story",icon:"✐",category:"Creative",mode:"creative",instructions:"Take turns adding to the story.",prompts:["We opened the door and could not believe…","The map had one final clue…","At midnight, both phones displayed…"]}
];

const MORE_PROMPTS:Record<string,string[]>={
knows:["My comfort food is…","The hobby I want to try is…","My ideal quiet evening is…","Something that always cheers me up is…","The season I enjoy most is…","My dream weekend includes…","The gift I appreciate most is…","The chore I avoid first is…","My favourite kind of surprise is…"],
guess:["The movie we should watch next","A meal we should cook together","Our perfect rainy-day plan","A place we should revisit","A tradition we should start","The funniest nickname between us","Our next photo should be at…","A skill we could learn together","The best way to celebrate good news"],
likely:["Who would start a sing-along?","Who remembers tiny details?","Who would pack too many snacks?","Who sends the funniest messages?","Who would adopt a plant first?","Who is better at directions?","Who would plan a themed night?","Who laughs first during a challenge?","Who would wake up earliest on a trip?"],
would:["Movie marathon or game marathon?","Picnic lunch or café breakfast?","Mountains or seaside?","Matching outfits or matching playlists?","Try a new recipe or perfect an old one?","Photos or handwritten notes?","Early adventure or late-night chat?","Big celebration or cosy evening?","Mystery plan or planned itinerary?"],
finish:["I feel most supported when…","A little thing I adore is…","Our best team moment was…","I cannot help smiling when…","One adventure on my list is…","We make a great team because…","A tradition I hope we keep is…","You surprised me when…","The next memory I want to make is…"],
memory:["Remember a day that went better than planned.","Describe a moment when you felt proud of each other.","What shared joke still works every time?","Recall your favourite conversation together.","Describe a thoughtful little gesture you remember.","Which photo brings back the clearest memory?","Recall a time you solved a problem together.","What ordinary day became unexpectedly special?","Describe a moment you both could not stop laughing."],
timeline:["Place your first three favourite outings in order.","Order three memorable messages or calls.","List three milestones from earliest to latest.","Which came first: a shared joke or a shared playlist?","Order three celebrations you remember.","Name the season of three important memories.","Place three favourite photos in time order.","Which plan did you make together first?","Build a five-event mini timeline of your story."],
said:["We should save that idea for later.","I knew you were going to say that.","Wait, let me explain.","This is definitely going in our memories.","I am not laughing—okay, I am.","Send me that picture.","We make a pretty good team.","I have a better idea.","Remind me how this started again?"],
trivia:["Which planet is fifth from the Sun?","How many vertices does a hexagon have?","Which city is Jamaica’s capital?","Name the Solar System’s largest planet.","A six-sided polygon has how many sides?","What is Jamaica’s capital city?","Which gas giant is the largest planet?","How many corners are on a regular hexagon?","Kingston is the capital of which Caribbean country?"],
riddle:["What instrument has black and white keys but no locks?","What becomes wetter while doing its job of drying?","What has a face and hands but no arms?","I have many keys and pedals but open no doors. What am I?","I dry you while becoming wet. What am I?","I tick and have hands but cannot applaud. What am I?","My keys make music instead of opening locks. What am I?","I hang nearby and get wet when you get dry. What am I?","My hands travel all day around one face. What am I?"],
math:["9 × 14","36 ÷ 3","80 − 16","7 × 18","60 ÷ 5","32 + 32","21 × 6","96 ÷ 8","100 − 36"],
word:["A six-letter word beginning with S","Write a word that rhymes with night","Name a fruit with an A in its name","Enter any 6-letter S word","A rhyme for bright","A fruit whose spelling contains A","Give a six-letter word starting in S","Write one word that rhymes with light","Type a fruit containing the letter A"],
emoji:["☔🐈🐕","⌚💵","📚🐛","🌦️😺🐶","⏳🪙","📕🐞","🌧️ + cats + dogs","Time + money","Book + worm"],
memoryChallenge:["Memorize: ♡ ✦ ☻ ◈ ♕","Remember these digits: 7 2 9 4 1","Remember the colours: Red · Blue · Gold · Green","Study closely: ♡ ✦ ☻ ◈ ♕","Number sequence: 7-2-9-4-1","Colour order: Red, Blue, Gold, Green","Repeat exactly: ♡ ✦ ☻ ◈ ♕","Keep this order: 7 2 9 4 1","Keep this order: Red / Blue / Gold / Green"],
five:["Name 3 indoor activities","Name 3 green things","Name 3 movies you both like","Name 3 weekend plans","Name 3 round objects","Name 3 favourite snacks","Name 3 ways to celebrate","Name 3 things found in a kitchen","Name 3 places you want to visit"],
charades:["Opening a stubborn jar","Walking through heavy rain","Finding a surprise gift","Trying to catch a bus","Baking a cake","Taking the perfect photo","Getting lost with a map","Celebrating a victory","Building a blanket fort"],
dontsay:["School — don’t say teacher, class, student","Music — don’t say song, sound, listen","Rain — don’t say water, cloud, wet","Pizza — don’t say cheese, slice, food","Holiday — don’t say travel, break, vacation","Camera — don’t say photo, picture, lens","Garden — don’t say plant, flower, grow","Movie — don’t say film, watch, cinema","Clock — don’t say time, hands, tick"],
truth:["Use only funny everyday moments.","Use only school or work stories.","Use only hobbies and talents.","Use facts from the past year.","Use only favourite things.","Use only surprising experiences.","Use childhood games and interests.","Use travel or outing memories.","Make all three statements believable."],
describe:["Rainbow","Popcorn","A treasure map","A lighthouse","A surprise party","A bicycle","A waterfall","A library","A snowman"],
draw:["A cosy reading corner","A flying turtle","Your dream holiday","A robot making breakfast","A tiny island","A funny superhero","A magical treehouse","A pet wearing sunglasses","The world’s strangest vehicle"],
caption:["When we both choose the same answer…","Five minutes into game night…","When the plan actually works…","That moment the timer starts…","When your partner knows you too well…","Our faces after the final score…","When one snack becomes ten…","Trying to act completely normal…","When the group photo takes twenty tries…"],
story:["The package had no name, only a symbol…","We followed the music around the corner…","The old photo revealed a hidden message…","One ordinary morning, gravity paused…","The tiny key fit a door we had never noticed…","Our game-night score unlocked a secret level…","The notebook began writing by itself…","A friendly robot asked for one favour…","The final train arrived at an impossible station…"]
};

for(const game of GAMES) game.prompts.push(...(MORE_PROMPTS[game.key]||[]));
