export type GameMode="match"|"choice"|"text"|"speed"|"creative";
export type GameDef={key:string;title:string;icon:string;category:string;mode:GameMode;instructions:string;prompts:string[]};
export const GAMES:GameDef[]=[
{key:"knows",title:"Who Knows Me Better?",icon:"♡",category:"Couple",mode:"match",instructions:"Answer about yourself, then your partner predicts it.",prompts:["My perfect day includes…","My favourite way to relax is…","The snack I can never refuse is…"]},
{key:"guess",title:"Guess My Answer",icon:"✦",category:"Couple",mode:"match",instructions:"Write an answer and score when your answers match.",prompts:["Our funniest shared memory","A trip we should take","The song that reminds me of us"]},
{key:"likely",title:"Most Likely To",icon:"☻",category:"Couple",mode:"choice",instructions:"Choose which partner best fits the prompt.",prompts:["Who is most likely to plan a surprise?","Who takes longer to choose food?","Who would win a dance-off?"]},
{key:"would",title:"Would You Rather?",icon:"↔",category:"Couple",mode:"choice",instructions:"Choose privately, then reveal whether you agree.",prompts:["Beach sunrise or city night?","Plan every detail or be spontaneous?","Cook together or order your favourite meal?"]},
{key:"finish",title:"Finish My Sentence",icon:"…",category:"Couple",mode:"match",instructions:"Complete the sentence and predict your partner.",prompts:["I knew you understood me when…","We always laugh when…","Next year, I hope we…"]},
{key:"memory",title:"Memory Lane",icon:"⌁",category:"Couple",mode:"text",instructions:"Recall a shared moment; compare details together.",prompts:["Describe your first favourite memory together.","What small moment still makes you smile?","What was your best unexpected adventure?"]},
{key:"timeline",title:"Relationship Timeline",icon:"⌛",category:"Couple",mode:"text",instructions:"Place relationship moments in the correct order.",prompts:["List three important moments in order.","Which happened first: your first long call or first outing?","Name the month of a favourite milestone."]},
{key:"said",title:"Who Said It?",icon:"“",category:"Couple",mode:"choice",instructions:"Guess which partner said the quote.",prompts:["I could eat this every day.","Five more minutes, then I’m ready.","Let’s take one more picture."]},
{key:"trivia",title:"Trivia Battle",icon:"?",category:"Competitive",mode:"speed",instructions:"Answer correctly before your partner.",prompts:["What is the largest planet?","How many sides does a hexagon have?","What is the capital of Jamaica?"]},
{key:"riddle",title:"Riddle Battle",icon:"◈",category:"Competitive",mode:"speed",instructions:"Solve the riddle first.",prompts:["What has keys but opens no locks?","What gets wetter as it dries?","What has hands but cannot clap?"]},
{key:"math",title:"Math Battle",icon:"∑",category:"Competitive",mode:"speed",instructions:"Solve the equation before time expires.",prompts:["18 × 7","144 ÷ 12","35 + 48 − 19"]},
{key:"word",title:"Word Battle",icon:"Aa",category:"Competitive",mode:"speed",instructions:"Enter a valid word for the challenge.",prompts:["A 6-letter word starting with S","A word that rhymes with light","A fruit containing the letter A"]},
{key:"emoji",title:"Emoji Decoder",icon:"☺",category:"Competitive",mode:"speed",instructions:"Decode the emoji phrase.",prompts:["🌧️🐱🐶","⏰💰","📖🐛"]},
{key:"memoryChallenge",title:"Memory Challenge",icon:"▦",category:"Competitive",mode:"speed",instructions:"Study the sequence, then reproduce it.",prompts:["♡ ✦ ☻ ◈ ♕","7 2 9 4 1","Red · Blue · Gold · Green"]},
{key:"five",title:"5 Second Challenge",icon:"5",category:"Party",mode:"speed",instructions:"Name three things before time runs out.",prompts:["Name 3 date ideas","Name 3 things that are blue","Name 3 songs you both know"]},
{key:"charades",title:"Charades",icon:"♙",category:"Party",mode:"creative",instructions:"Act out the prompt without speaking.",prompts:["Taking a selfie","Missing the bus","Winning a race"]},
{key:"dontsay",title:"Don’t Say It",icon:"×",category:"Party",mode:"text",instructions:"Describe the word without using the forbidden clues.",prompts:["Beach — don’t say sand, sea, water","Birthday — don’t say cake, age, party","Phone — don’t say call, screen, text"]},
{key:"truth",title:"Two Truths & a Lie",icon:"≋",category:"Party",mode:"text",instructions:"Write three statements; your partner spots the lie.",prompts:["Write your two truths and one lie.","Use only childhood memories.","Use only food and travel facts."]},
{key:"describe",title:"Describe & Guess",icon:"◎",category:"Party",mode:"text",instructions:"Describe the secret prompt for your partner.",prompts:["Sunset","Roller coaster","Birthday cake"]},
{key:"draw",title:"Drawing Battle",icon:"✎",category:"Creative",mode:"creative",instructions:"Draw the prompt and let your partner guess.",prompts:["Dream house","A dancing cat","Your perfect weekend"]},
{key:"caption",title:"Caption This",icon:"“ ”",category:"Creative",mode:"creative",instructions:"Write the funniest caption; vote on the winner.",prompts:["When the food finally arrives…","That look when you both forgot…","Our next adventure starts like this…"]},
{key:"story",title:"Finish the Story",icon:"✐",category:"Creative",mode:"creative",instructions:"Take turns adding to the story.",prompts:["We opened the door and could not believe…","The map had one final clue…","At midnight, both phones displayed…"]}
];
