export type GameMode="match"|"choice"|"text"|"speed"|"creative";
export type GameDef={key:string;title:string;icon:string;category:string;mode:GameMode;instructions:string;prompts:string[]};
export const GAMES:GameDef[]=[
{key:"knows",title:"Who Knows Me Better?",icon:"♡",category:"Couple",mode:"match",instructions:"Answer about yourself, then your partner predicts it.",prompts:["My perfect day includes…","My favourite way to relax is…","The snack I can never refuse is…"]},
{key:"guess",title:"Guess My Answer",icon:"✦",category:"Couple",mode:"match",instructions:"Write an answer and score when your answers match.",prompts:["Our funniest shared memory","A trip we should take","The song that reminds me of us"]},
{key:"likely",title:"Most Likely To",icon:"☻",category:"Couple",mode:"choice",instructions:"Choose which partner best fits the prompt.",prompts:["Who is most likely to plan a surprise?","Who takes longer to choose food?","Who would win a dance-off?"]},
{key:"would",title:"Would You Rather?",icon:"↔",category:"Couple",mode:"choice",instructions:"Choose privately, then reveal whether you agree.",prompts:["Beach sunrise or city night?","Plan every detail or be spontaneous?","Cook together or order your favourite meal?"]},
{key:"finish",title:"Finish My Sentence",icon:"…",category:"Couple",mode:"match",instructions:"Complete the sentence and predict your partner.",prompts:["I knew you understood me when…","We always laugh when…","Next year, I hope we…"]},
{key:"memory",title:"Memory Lane",icon:"⌁",category:"Couple",mode:"text",instructions:"Recall a shared moment; compare details together.",prompts:["Describe your first favourite memory together.","What small moment still makes you smile?","What was your best unexpected adventure?"]},
{key:"timeline",title:"Relationship Timeline",icon:"⌛",category:"Couple",mode:"text",instructions:"Place relationship moments in the correct order.",prompts:["List three important moments in order.","Which happened first: your first long call or first outing?","Name the month of a favourite milestone."]},
{key:"said",title:"Who Said It?",icon:"“",category:"Couple",mode:"choice",instructions:"Guess which partner said the quote.",prompts:["I could eat this every day.","Five more minutes, then I’m ready.","Let’s take one more picture."]},
{key:"trivia",title:"Trivia Battle",icon:"?",category:"Competitive",mode:"speed",instructions:"Answer correctly before your partner.",prompts:["What is the largest planet?","How many sides does a hexagon have?","What is the capital of Jamaica?"]},
{key:"riddle",title:"Riddle Battle",icon:"◈",category:"Competitive",mode:"speed",instructions:"Solve the riddle first.",prompts:["What has keys but opens no locks?","What gets wetter as it dries?","What has hands but cannot clap?"]},
{key:"math",title:"Math Battle",icon:"∑",category:"Competitive",mode:"speed",instructions:"Solve the equation before time expires.",prompts:["18 × 7","144 ÷ 12","35 + 48 − 19"]},
{key:"word",title:"Word Battle",icon:"Aa",category:"Competitive",mode:"speed",instructions:"Enter a valid word for the challenge.",prompts:["A 6-letter word starting with S","A word that rhymes with light","A fruit containing the letter A"]},
{key:"emoji",title:"Emoji Decoder",icon:"☺",category:"Competitive",mode:"speed",instructions:"Decode the emoji phrase.",prompts:["🌧️🐱🐶","⏰💰","📖🐛"]},
{key:"memoryChallenge",title:"Memory Challenge",icon:"▦",category:"Competitive",mode:"speed",instructions:"Study the sequence, then reproduce it.",prompts:["♡ ✦ ☻ ◈ ♕","7 2 9 4 1","Red · Blue · Gold · Green"]},
{key:"five",title:"5 Second Challenge",icon:"5",category:"Party",mode:"speed",instructions:"Name three things before time runs out.",prompts:["Name 3 date ideas","Name 3 things that are blue","Name 3 songs you both know"]},
{key:"charades",title:"Charades",icon:"♙",category:"Party",mode:"creative",instructions:"Act out the prompt without speaking.",prompts:["Taking a selfie","Missing the bus","Winning a race"]},
{key:"dontsay",title:"Don’t Say It",icon:"×",category:"Party",mode:"text",instructions:"Describe the word without using the forbidden clues.",prompts:["Beach — don’t say sand, sea, water","Birthday — don’t say cake, age, party","Phone — don’t say call, screen, text"]},
{key:"truth",title:"Two Truths & a Lie",icon:"≋",category:"Party",mode:"text",instructions:"Write three statements; your partner spots the lie.",prompts:["Write your two truths and one lie.","Use only childhood memories.","Use only food and travel facts."]},
{key:"describe",title:"Describe & Guess",icon:"◎",category:"Party",mode:"text",instructions:"Describe the secret prompt for your partner.",prompts:["Sunset","Roller coaster","Birthday cake"]},
{key:"draw",title:"Drawing Battle",icon:"✎",category:"Creative",mode:"creative",instructions:"Draw the prompt and let your partner guess.",prompts:["Dream house","A dancing cat","Your perfect weekend"]},
{key:"caption",title:"Caption This",icon:"“ ”",category:"Creative",mode:"creative",instructions:"Write the funniest caption; vote on the winner.",prompts:["When the food finally arrives…","That look when you both forgot…","Our next adventure starts like this…"]},
{key:"story",title:"Finish the Story",icon:"✐",category:"Creative",mode:"creative",instructions:"Take turns adding to the story.",prompts:["We opened the door and could not believe…","The map had one final clue…","At midnight, both phones displayed…"]}
];

const MORE_PROMPTS:Record<string,string[]>={
knows:["My comfort food is…","The hobby I want to try is…","My ideal quiet evening is…","Something that always cheers me up is…","The season I enjoy most is…","My dream weekend includes…","The gift I appreciate most is…","The chore I avoid first is…","My favourite kind of surprise is…"],
guess:["The movie we should watch next","A meal we should cook together","Our perfect rainy-day plan","A place we should revisit","A tradition we should start","The funniest nickname between us","Our next photo should be at…","A skill we could learn together","The best way to celebrate good news"],
likely:["Who would start a sing-along?","Who remembers tiny details?","Who would pack too many snacks?","Who sends the funniest messages?","Who would adopt a plant first?","Who is better at directions?","Who would plan a themed night?","Who laughs first during a challenge?","Who would wake up earliest on a trip?"],
would:["Movie marathon or game marathon?","Picnic lunch or café breakfast?","Mountains or seaside?","Matching outfits or matching playlists?","Try a new recipe or perfect an old one?","Photos or handwritten notes?","Early adventure or late-night chat?","Big celebration or cosy evening?","Mystery plan or planned itinerary?"],
finish:["I feel most supported when…","A little thing I adore is…","Our best team moment was…","I cannot help smiling when…","One adventure on my list is…","We make a great team because…","A tradition I hope we keep is…","You surprised me when…","The next memory I want to make is…"],
memory:["Remember a day that went better than planned.","Describe a moment when you felt proud of each other.","What shared joke still works every time?","Recall your favourite conversation together.","Describe a thoughtful little gesture you remember.","Which photo brings back the clearest memory?","Recall a time you solved a problem together.","What ordinary day became unexpectedly special?","Describe a moment you both could not stop laughing."],
timeline:["Place your first three favourite outings in order.","Order three memorable messages or calls.","List three milestones from earliest to latest.","Which came first: a shared joke or a shared playlist?","Order three celebrations you remember.","Name the season of three important memories.","Place three favourite photos in time order.","Which plan did you make together first?","Build a five-event mini timeline of your story."],
said:["We should save that idea for later.","I knew you were going to say that.","Wait, let me explain.","This is definitely going in our memories.","I am not laughing—okay, I am.","Send me that picture.","We make a pretty good team.","I have a better idea.","Remind me how this started again?"],
trivia:["Which planet is fifth from the Sun?","How many vertices does a hexagon have?","Which city is Jamaica’s capital?","Name the Solar System’s largest planet.","A six-sided polygon has how many sides?","What is Jamaica’s capital city?","Which gas giant is the largest planet?","How many corners are on a regular hexagon?","Kingston is the capital of which Caribbean country?"],
riddle:["What instrument has black and white keys but no locks?","What becomes wetter while doing its job of drying?","What has a face and hands but no arms?","I have many keys and pedals but open no doors. What am I?","I dry you while becoming wet. What am I?","I tick and have hands but cannot applaud. What am I?","My keys make music instead of opening locks. What am I?","I hang nearby and get wet when you get dry. What am I?","My hands travel all day around one face. What am I?"],
math:["9 × 14","36 ÷ 3","80 − 16","7 × 18","60 ÷ 5","32 + 32","21 × 6","96 ÷ 8","100 − 36"],
word:["A six-letter word beginning with S","Write a word that rhymes with night","Name a fruit with an A in its name","Enter any 6-letter S word","A rhyme for bright","A fruit whose spelling contains A","Give a six-letter word starting in S","Write one word that rhymes with light","Type a fruit containing the letter A"],
emoji:["☔🐈🐕","⌚💵","📚🐛","🌦️😺🐶","⏳🪙","📕🐞","🌧️ + cats + dogs","Time + money","Book + worm"],
memoryChallenge:["Memorize: ♡ ✦ ☻ ◈ ♕","Remember these digits: 7 2 9 4 1","Remember the colours: Red · Blue · Gold · Green","Study closely: ♡ ✦ ☻ ◈ ♕","Number sequence: 7-2-9-4-1","Colour order: Red, Blue, Gold, Green","Repeat exactly: ♡ ✦ ☻ ◈ ♕","Keep this order: 7 2 9 4 1","Keep this order: Red / Blue / Gold / Green"],
five:["Name 3 indoor activities","Name 3 green things","Name 3 movies you both like","Name 3 weekend plans","Name 3 round objects","Name 3 favourite snacks","Name 3 ways to celebrate","Name 3 things found in a kitchen","Name 3 places you want to visit"],
charades:["Opening a stubborn jar","Walking through heavy rain","Finding a surprise gift","Trying to catch a bus","Baking a cake","Taking the perfect photo","Getting lost with a map","Celebrating a victory","Building a blanket fort"],
dontsay:["School — don’t say teacher, class, student","Music — don’t say song, sound, listen","Rain — don’t say water, cloud, wet","Pizza — don’t say cheese, slice, food","Holiday — don’t say travel, break, vacation","Camera — don’t say photo, picture, lens","Garden — don’t say plant, flower, grow","Movie — don’t say film, watch, cinema","Clock — don’t say time, hands, tick"],
truth:["Use only funny everyday moments.","Use only school or work stories.","Use only hobbies and talents.","Use facts from the past year.","Use only favourite things.","Use only surprising experiences.","Use childhood games and interests.","Use travel or outing memories.","Make all three statements believable."],
describe:["Rainbow","Popcorn","A treasure map","A lighthouse","A surprise party","A bicycle","A waterfall","A library","A snowman"],
draw:["A cosy reading corner","A flying turtle","Your dream holiday","A robot making breakfast","A tiny island","A funny superhero","A magical treehouse","A pet wearing sunglasses","The world’s strangest vehicle"],
caption:["When we both choose the same answer…","Five minutes into game night…","When the plan actually works…","That moment the timer starts…","When your partner knows you too well…","Our faces after the final score…","When one snack becomes ten…","Trying to act completely normal…","When the group photo takes twenty tries…"],
story:["The package had no name, only a symbol…","We followed the music around the corner…","The old photo revealed a hidden message…","One ordinary morning, gravity paused…","The tiny key fit a door we had never noticed…","Our game-night score unlocked a secret level…","The notebook began writing by itself…","A friendly robot asked for one favour…","The final train arrived at an impossible station…"]
};

for(const game of GAMES) game.prompts.push(...(MORE_PROMPTS[game.key]||[]));

const LENSES=[
"Answer from your first instinct","Think about the past month","Think about the past year","Choose what fits you today",
"Imagine your next free weekend","Think of an ordinary weekday","Use a memory you have not shared lately","Choose the answer that would surprise your partner"
];
const JUPITER_CLUES=["Which planet is the largest in our Solar System?","Which planet is fifth from the Sun?","Which planet has the Great Red Spot?","Which gas giant has the shortest day?","Which planet has over ninety known moons?","Which planet is named for the Roman king of the gods?","Which planet is more massive than all the other planets combined?","Which planet lies between Mars and Saturn?","Which striped gas giant is famous for a giant storm?","Which planet’s moon Ganymede is the Solar System’s largest moon?","Which planet’s four largest moons were observed by Galileo?","Which planet is mostly hydrogen and helium and is the biggest planet?","Which planet has moons named Io, Europa and Callisto?","Which planet takes almost twelve Earth years to orbit the Sun?","Which planet has a faint ring system and a Great Red Spot?","Which planet is about eleven times wider than Earth?","Which planet has cloud bands called belts and zones?","Which planet is the Solar System’s second-brightest planet from Earth after Venus?","Which planet has a powerful magnetic field and is the largest gas giant?","Which world did the Juno spacecraft enter orbit around?","Which planet was visited by the Galileo orbiter?","Which planet has a storm called the Great Red Spot?","Which planet is the first gas giant moving outward from the Sun?","Which planet is associated with the adjective Jovian?","Which planet’s mass is about 318 Earths?","Which planet has a moon called Europa?","Which planet is famous for alternating light and dark cloud bands?","Which planet rotates once in roughly ten hours?","Which planet has the strongest gravity among the Solar System’s planets?","Which planet is the biggest member of the Sun’s planetary family?"],
SIX_CLUES=["How many sides does a hexagon have?","How many vertices does a hexagon have?","What is 3 + 3?","What is 12 ÷ 2?","How many faces does a cube have?","How many strings does a standard guitar usually have?","What is 2 × 3?","How many legs do three birds have?","What number comes after five?","What is 10 − 4?","How many dots are on the highest face of a standard die?","How many letters are in the word planet?","What is 18 ÷ 3?","How many months make half a year?","What is the square root of 36?","How many points are on a traditional Star of David?","What is 7 − 1?","How many items are in half a dozen?","What is 24 ÷ 4?","How many zeros are in one million?","How many letters are in the word couple?","What is 30 ÷ 5?","How many equal sides does a regular hexagon have?","What is 4 + 2?","How many wheels are on three bicycles?","What is 42 ÷ 7?","How many pairs make twelve items?","What is 8 − 2?","How many letters are in the word Friday?","What is 54 ÷ 9?"],
KINGSTON_CLUES=["What is the capital of Jamaica?","Which Jamaican city is the national capital?","Which city is home to Jamaica’s Parliament?","Which city contains Jamaica’s National Heroes Park?","Which city is Jamaica’s largest metropolitan area and capital?","Which capital city sits on Jamaica’s southeast coast?","Which Jamaican city includes the historic Port Royal area?","Which city is the seat of Jamaica’s national government?","Which city is home to the Bob Marley Museum?","Which capital city lies beside the world’s seventh-largest natural harbour?","Which Jamaican city is served by Norman Manley International Airport?","Which city was made Jamaica’s capital in 1872?","Which city replaced Spanish Town as Jamaica’s capital?","Which Jamaican city includes downtown and New Kingston?","Which city is home to Devon House?","Which city hosts Jamaica’s main government ministries?","Which Jamaican capital faces Kingston Harbour?","Which city is the commercial centre of Jamaica?","Which city is home to the University of the West Indies Mona campus area?","Which Jamaican city has communities called Half Way Tree and Cross Roads?","Which city contains Emancipation Park?","Which city is Jamaica’s cultural and administrative capital?","Which Caribbean capital is located in the parish of Kingston and St Andrew?","Which Jamaican city is overlooked by the Blue Mountains?","Which city has a waterfront near Ocean Boulevard?","Which city is associated with the historic Ward Theatre?","Which Jamaican capital includes the National Gallery of Jamaica?","Which city’s harbour is protected by the Palisadoes?","Which Jamaican city is often abbreviated KGN?","Name Jamaica’s capital and largest city."],
PIANO_CLUES=["What has keys but opens no locks?","What has black and white keys and makes music?","What instrument has keys, pedals and strings?","What can be grand, upright or electric and has keys?","I have eighty-eight keys but no doors. What am I?","Which instrument is played by pressing rows of keys?","I make melodies when fingers touch my keys. What am I?","My keys are musical, not for locks. What am I?","What instrument may have a lid, bench and pedals?","I can be tuned but I am not a radio, and I have keys. What am I?","What instrument has hammers that strike strings when keys are pressed?","What keyboard instrument can be grand or upright?","I sit in music rooms and my keys are black and white. What am I?","My player uses both hands and sometimes both feet. What am I?","What instrument did Mozart commonly compose for that has keys?","I have a keyboard but I am not a computer. What am I?","Press my keys softly or loudly to change my sound. What am I?","What instrument’s name begins with P and ends with O?","I can accompany a singer and have eighty-eight keys. What am I?","What instrument uses a sustain pedal?","My middle C is near the centre of my keyboard. What am I?","I produce notes through felt-covered hammers. What am I?","What instrument might be found in a concert hall with its lid raised?","What musical object has sharps and flats across its keys?","I am too large for a pocket but full of keys. What am I?","What instrument can play melody and harmony at once using keys?","I am an acoustic keyboard instrument with strings inside. What am I?","What instrument is commonly paired with a small bench?","My soft pedal changes my tone. What am I?","What keyed instrument is central to many classical recitals?"],
TOWEL_CLUES=["What gets wetter as it dries?","I dry you but become wet. What am I?","What hangs in a bathroom and absorbs water?","You use me after a shower, and I get wetter while helping. What am I?","What cloth dries dishes while becoming damp?","I start dry and end wet when I do my job. What am I?","What do you wrap around yourself after swimming?","I absorb water from your hands. What am I?","What bathroom item is washed even though it cleans up water?","I may be folded on a rack and used to dry. What am I?","What fabric item waits beside a sink or shower?","I am soft, absorbent and wetter after drying you. What am I?","What do athletes use to wipe away sweat?","What is often hung on a rail after use?","What beach item can dry both you and itself in the sun?","I am not a sponge, but I absorb water and dry skin. What am I?","What linen item is used after bathing?","What do you reach for with wet hands?","What can be hand-sized, bath-sized or beach-sized?","I get damp when I make something else dry. What am I?","What household cloth is made with absorbent loops?","What item might say HIS or HERS and hang in a bathroom?","I can be rolled at a hotel and used after a shower. What am I?","What do you use to pat your face dry?","What cloth belongs in both kitchens and bathrooms?","What is commonly stored in a linen closet and used for drying?","I soak up spills but am not a mop. What am I?","What do swimmers carry to the pool to dry off?","What can be fluffy, folded and absorbent?","What everyday item becomes wet by removing water?"],
CLOCK_CLUES=["What has hands but cannot clap?","What has a face and hands but no arms?","What tells time with moving hands?","My hands travel but never leave my face. What am I?","I may tick but I am not alive. What am I?","What hangs on a wall and has twelve numbers?","I have an hour hand but no fingers. What am I?","What object may chime at the top of the hour?","I measure the day but never move from my spot. What am I?","What has minute and second hands?","I can be digital or analogue and help you stay on time. What am I?","What object’s face may show Roman numerals?","I run all day without feet and sometimes tick. What am I?","What tells you when it is time for game night?","My hands circle my face every day. What am I?","What timepiece might sit on a wall or desk?","What can strike twelve without hitting anything?","What device has an hour hand and a minute hand?","I keep time but cannot keep a secret. What am I?","What object may be fast or slow despite never walking?","What has a second hand but no first hand?","I may have an alarm and a face. What am I?","What object divides its face into twelve hours?","What ticks in a quiet room?","I tell time without speaking. What am I?","What can be wound up and still stay in one place?","My hands meet at noon and midnight. What am I?","What timekeeper may use gears and springs?","What object shows 3:00 with one hand at three and one at twelve?","What common object has hands that point to numbers?"],
FIVE_TOPICS=["breakfast foods","yellow things","board games","Caribbean countries","animals with four legs","things found at school","ways to say hello","items in a backpack","fruits","vegetables","things that fly","water activities","musical instruments","things in a bedroom","outdoor games","round foods","cold things","things with buttons","types of weather","things at a party","things people collect","jobs","things in a car","items in a kitchen","things that glow","places in a town","things made of paper","things with wheels","quiet activities","reasons to smile"];

function speedPrompt(key:string,index:number){
  const slot=index%3, set=Math.floor(index/3);
  if(key==="trivia") return `${[JUPITER_CLUES,SIX_CLUES,KINGSTON_CLUES][slot][set%30]} · card ${set+1}`;
  if(key==="riddle") return `${[PIANO_CLUES,TOWEL_CLUES,CLOCK_CLUES][slot][set%30]} · card ${set+1}`;
  if(key==="math") return slot===0?`${120-set} + ${6+set}`:slot===1?`${60+set*12} ÷ ${5+set}`:`${80+set} − ${16+set}`;
  if(key==="word") return slot===0?`Enter a six-letter word beginning with S — round ${set+1}`:slot===1?`Enter a word that rhymes with light — round ${set+1}`:`Enter a fruit containing A — round ${set+1}`;
  if(key==="emoji") return slot===0?`Decode: ${["🌧️🐱🐶","☔🐈🐕","🌦️😺🐶"][set%3]} · card ${set+1}`:slot===1?`Decode: ${["⏰💰","⌚💵","⏳🪙"][set%3]} · card ${set+1}`:`Decode: ${["📖🐛","📚🐛","📕🐞"][set%3]} · card ${set+1}`;
  if(key==="memoryChallenge") return slot===0?`Study and repeat: ♡ ✦ ☻ ◈ ♕ · set ${set+1}`:slot===1?`Study and repeat: 7 2 9 4 1 · set ${set+1}`:`Study and repeat: Red · Blue · Gold · Green · set ${set+1}`;
  return `Name 3 ${FIVE_TOPICS[index%FIVE_TOPICS.length]} — challenge ${index+1}`;
}

for(const game of GAMES){
  const original=[...game.prompts];
  for(let attempt=0;game.prompts.length<100&&attempt<500;attempt++){
    const index=original.length+attempt;
    const prompt=game.mode==="speed"
      ? speedPrompt(game.key,index)
      : `${original[index%original.length]} (${LENSES[Math.floor(index/original.length)%LENSES.length].toLowerCase()}.)`;
    if(!game.prompts.includes(prompt)) game.prompts.push(prompt);
  }
  while(game.prompts.length<100) game.prompts.push(`${original[game.prompts.length%original.length]} (fresh card ${game.prompts.length+1}.)`);
  game.prompts=game.prompts.slice(0,100);
}
